Check to Haris kang review :v
farelamo/Free-News pull request #3
Opened 2021-12-04 11:56 UTC by farelamo

2021-12-04 12:08 UTC, harisfi requested changes
Fix to kang Fariz :smile:

2021-12-04 12:08 UTC, harisfi commented on app/Http/Controllers/Auth/RegisterController.php
>              'password' => Hash::make($data['password']),
bisa langsung menggunakan fungsi helper **bcrypt**

2021-12-04 12:08 UTC, harisfi commented on app/Http/Controllers/profileController.php
> +        $eUser = User::where('profile_id', $id)->first();
bisa langsung menggunakan method **get** karena id sudah PK

2021-12-04 12:08 UTC, harisfi commented on app/Models/Profile.php
> +    protected $fillable = ['name', 'username', 'bio'];
jika sudah ada $guarded maka tidak perlu $fillable

2021-12-04 12:08 UTC, harisfi commented on app/Models/User.php
> +        return $this->belongsTo(Profiles::class, 'id');
fungsi **belongsTo** sudah otomatis ke kolom id, maka penambahan ini kurang optimal

2021-12-14 12:21 UTC, farelamo commented on app/Http/Controllers/profileController.php
> +        $eUser = User::where('profile_id', $id)->first();
sek durung nangkep maksudte ngab wkkw

2021-12-14 12:31 UTC, merged